Add badges
gluetool/gluetool pull request #2
Opened 2018-01-23 14:42 UTC by happz

2018-01-24 08:24 UTC, happz commented
+1

2018-01-24 12:20 UTC, mkluson approved these changes
LGTM

2018-01-24 12:21 UTC, mkluson approved these changes
LGTM

2018-01-24 12:27 UTC, mkluson commented
+1

2018-01-24 12:27 UTC, mkluson approved these changes
+1

2018-01-24 12:42 UTC, mkluson requested changes
foo

2018-01-24 12:44 UTC, mkluson commented
+1 ok, accepted

2018-01-24 12:44 UTC, mkluson commented
+1

2018-01-24 12:45 UTC, mkluson reviewed
+1

2018-01-24 12:45 UTC, mkluson approved these changes

2018-01-24 12:52 UTC, mkluson requested changes
please

2018-01-24 12:52 UTC, mkluson commented on README.rst
> +.. image:: https://requires.io/github/gluetool/gluetool-test/requirements.svg?branch=master
THis sucks

2018-01-24 12:52 UTC, mkluson commented on README.rst
> +     :alt: Requirements Status
This sucks too

2018-01-24 12:53 UTC, happz commented on README.rst
> +.. image:: https://requires.io/github/gluetool/gluetool-test/requirements.svg?branch=master
trhni si

2018-01-24 12:54 UTC, happz commented on README.rst
> +     :alt: Requirements Status
+1

2018-01-24 12:55 UTC, happz reviewed
abc

2018-01-29 09:06 UTC, mkluson approved these changes
Finally approved. Previous comments had testing purpose.

2018-01-29 09:37 UTC, thrix commented
Awesome change!

2018-01-29 09:38 UTC, thrix submitted a review, later dismissed
Awesome change, really!

2018-01-29 09:41 UTC, happz commented
@mkluson @thrix Please, approve once again - I rebased the branch, which in turn invalidates your review :)

2018-01-29 09:42 UTC, mkluson approved these changes
LGTM

2018-01-29 09:50 UTC, thrix approved these changes
LGTM now

2018-01-29 09:51 UTC, merged