Add module's shared functions even when its execute() raised an excep…
gluetool/gluetool pull request #29
Opened 2018-05-09 06:54 UTC by happz

…tion

We want to give a module chance to provide at least some level of its
functionality even when it killed the pipeline. By our observations,
quite often following modules are interested in data the culprit could
provide, even when they migh be incomplete.

2018-05-13 22:50 UTC, thrix commented
otherwise LGTM

2018-05-14 06:49 UTC, happz commented
@thrix "otherwise"? :) I see no comments (and no "Approved" as well :)

2018-05-14 07:03 UTC, thrix commented
@happz hmm, I do not see addressed my two small comments? ^

2018-05-14 07:21 UTC, happz commented
@thrix Nope, I don't see them. Anyway, I changed the comment, based on the image you sent. Ready for review.

2018-05-14 07:56 UTC, thrix requested changes

2018-05-14 07:56 UTC, thrix commented on gluetool/glue.py
> +                # In case ``add_shared`` crashes, the exception is not lost since it's already
maybe change the wording please. ```the exception``` -> ```the previous execption```

2018-05-14 07:56 UTC, thrix commented on gluetool/glue.py
> +                # In case ``add_shared`` crashes, the exception is not lost since it's already
or even ```the previous exception from execute```

2018-05-14 07:56 UTC, thrix commented on gluetool/tests/test_run_modules.py
> +def test_core_add_shared(glue):
why is this here?

2018-05-14 08:01 UTC, happz commented on gluetool/tests/test_run_modules.py
> +def test_core_add_shared(glue):
Ah, right. I copy & pasted some test cases to refactor them, and didn't remove the rest. Removed.

2018-05-14 08:02 UTC, happz commented on gluetool/glue.py
> +                # In case ``add_shared`` crashes, the exception is not lost since it's already
Should be fixed.

2018-05-14 09:14 UTC, thrix approved these changes
LGTM now

2018-05-16 07:56 UTC, happz commented
Given there are no other reviewers available at this moment, going to merge with just a single review.

2018-05-16 07:57 UTC, merged