Verbose logging goes into separate file
gluetool/gluetool pull request #30
Opened 2018-05-14 09:08 UTC by happz

DEBUG logging reached huge amounts of text, making examination of common
"debug" log files hard. Also, we're not using "verbose" logging anyway,
so the idea is to use it for logging blobs and long texts - those that
are usually not that interesting in debug log, but might be very useful
when we need to debug weird behavior - API responses, HTTP
communication, command output, eval context gathering.

This patch repurposes our "verbose" logging. Every "verbose" call
creates a tag for the given message, logs this tag with normal DEBUG
level, and then logs the message with VERBOSE level. Special file
handler is added, it ignores any other level except the VERBOSE, and by
combining these two approaches we get a file with VERBOSE messages only,
and a debug output, both connected via the aforementioned tags, making
it possible to take a look into verbose file for bits that were omitted
from a debug log.

2018-05-14 09:09 UTC, happz commented
Open for review, but it *will* need changes when #28 gets merged since that touches logging as well. But that'd be just careful merge instead of rewrite.

2018-05-24 12:22 UTC, mkluson submitted a review, later dismissed

2018-05-25 08:03 UTC, thrix requested changes
@happz looks good. I would have maybe one suggestion. What about creating the verbose file by default if -o debug specified, with a .verbose suffix. The thing is if somebody runs ```-d -o debug``` the logs will tell him to see the verbose log, but actually, there is none, because he did not specify the --verobose-file option.

Also it would be nice to, in case there was no debug output file specified, display the verbose log or tell the user that to save the verbose log he needs to specify an option, instead of referencing an unexisting "verbose" file.

2018-05-25 08:03 UTC, thrix commented
@happz looks good. I would have maybe one suggestion. What about creating the verbose file by default if -o debug specified, with a .verbose suffix. The thing is if somebody runs ```-d -o debug``` the logs will tell him to see the verbose log, but actually, there is none, because he did not specify the --verobose-file option.

Also it would be nice to, in case there was no debug output file specified, display the verbose log or tell the user that to save the verbose log he needs to specify an option, instead of referencing an unexisting "verbose" file.

2018-05-29 15:51 UTC, happz commented
@thrix Ok, `-o/--debug-file` specifies the file for debug-level output. The default value of `--verbose-file` would be `--debug-file` with `.verbose` suffix, the user can of course set other name by actually using `--verbose-file` option.

WRT no debug file specified - this is the scenario when user runs `gluetool -d foo`, debugging mode but no `debug-file` nor `verbose-file`, right? Under such conditions, `DEBUG` messages would go to terminal only, with no `verbose` destination. Ok, we're already dumping debugging messages to the terminal, we can display `VERBOSE` level as well, that should work. It would be messy but if that's what user wants, he's gonna get it.

2018-05-29 21:16 UTC, thrix commented
> @thrix Ok, -o/--debug-file specifies the file for debug-level output. The default value of --verbose-file would be --debug-file with .verbose suffix, the user can of course set other name by actually using --verbose-file option.

Cool, agreed

> WRT no debug file specified - this is the scenario when user runs gluetool -d foo, debugging mode but no debug-file nor verbose-file, right? 

yep

> Under such conditions, DEBUG messages would go to terminal only, with no verbose destination. Ok, we're already dumping debugging messages to the terminal, we can display VERBOSE level as well, that should work. It would be messy but if that's what user wants, he's gonna get it.

Agreed, sounds good to me.

2018-06-05 10:43 UTC, happz commented
@thrix Hm, if we dump `VERBOSE` messages to screen when `-d` is used without any logging file, then `-v` option makes no sense anymore.

2018-06-07 07:02 UTC, thrix commented
> @thrix Hm, if we dump VERBOSE messages to screen when -d is used without any logging file, then -v option makes no sense anymore.

Hmm, that is true ...

> EDIT: I think instead of dumping VERBOSE to screen when -d is used and no --verbose-file, gluetool should just display a warning, telling user to either use -v or --verbose-file.

Sounds reasonable. Tested manually and works for me quite nicely.

2018-06-07 07:03 UTC, thrix submitted a review, later dismissed
LGTM. nice feature. I guess we will need to udpate our jobs to use verbose file.

2018-06-11 17:24 UTC, optak submitted a review, later dismissed
LGTM

2018-06-11 19:04 UTC, thrix commented
@happz seems some tests need fixing

2018-07-30 05:53 UTC, happz commented
Hm, patch coverage dropped somehow, while the overall coverage got better. Weird. I'm willing to waive it. Any objections?

@thrix @optak @mkluson Please, give it another spin, I fixed tests and applied the changes suggested in the discussion.

2018-07-30 08:23 UTC, thrix commented
No, no objectsion ...

2018-07-30 15:40 UTC, optak approved these changes
I checked latest changes and found no problem

2018-08-02 10:06 UTC, merged